name: Deploy the Infrastructure for an Azure Kubernetes Cluster
on: 
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  provision-monitoring:
    uses: ./.github/workflows/provision-monitoring.yml
    secrets: inherit
    
  provision-identity:
    uses: ./.github/workflows/provision-identity.yml
    secrets: inherit
  
  provision-networking:
    uses: ./.github/workflows/provision-networking.yml
    secrets: inherit
    needs: [provision-monitoring]
    with:
      logAnalyticsWorkspaceResourceId: ${{ needs.provision-monitoring.outputs.logAnalyticsWorkspaceResourceId }}